### ISSUE TITLE
Find out how @RoosterDragon profiles performance in OpenRA.

### ISSUE THREAD

**Issue by LavenderMoon** [LavenderMoon/Docs#1]
@RoosterDragon, what tool do you use to profile the performance optimizations you make to OpenRA?

**Comment by RoosterDragon** [comment]
For CPU profiling, I use the sampling profiler that comes with VS: https://msdn.microsoft.com/en-us/library/dd264994.aspx#sampling.

VS also has some memory profilers, but I find the free Microsoft tool, CLRProfiler to be more intuitive with its graphical display. Takes a little getting used to but pretty effective once you get your head around it. http://clrprofiler.codeplex.com/releases/view/97738

You can get both of those free on Windows, there's plenty of other tools both free and commercial and I'm sure there's some non-Windows tools as well. I wouldn't be surprised if mono provided some stuff. Both of the above include documentation and help to get you going.

Once you have the tools, run the game under the conditions you want to profile. Then stare at the output and see if anything jumps out. Make some changes and profile again to see if it actually helped or not. Rinse and repeat until you have something that makes a measurable change.

**Comment by LavenderMoon** [comment]
Thanks!
